# Generated by Django 3.1.6 on 2022-03-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('online_time', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='client_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'set',
            },
        ),
    ]
